//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.10.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from E:\resource\antlr-output2\python\python3\Python3Parser.g4 by ANTLR 4.10.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="Python3Parser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.10.1")]
[System.CLSCompliant(false)]
public interface IPython3ParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.single_input"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSingle_input([NotNull] Python3Parser.Single_inputContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.single_input"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSingle_input([NotNull] Python3Parser.Single_inputContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.file_input"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFile_input([NotNull] Python3Parser.File_inputContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.file_input"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFile_input([NotNull] Python3Parser.File_inputContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.eval_input"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEval_input([NotNull] Python3Parser.Eval_inputContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.eval_input"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEval_input([NotNull] Python3Parser.Eval_inputContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.decorator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDecorator([NotNull] Python3Parser.DecoratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.decorator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDecorator([NotNull] Python3Parser.DecoratorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.decorators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDecorators([NotNull] Python3Parser.DecoratorsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.decorators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDecorators([NotNull] Python3Parser.DecoratorsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.decorated"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDecorated([NotNull] Python3Parser.DecoratedContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.decorated"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDecorated([NotNull] Python3Parser.DecoratedContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.async_funcdef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAsync_funcdef([NotNull] Python3Parser.Async_funcdefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.async_funcdef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAsync_funcdef([NotNull] Python3Parser.Async_funcdefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.funcdef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncdef([NotNull] Python3Parser.FuncdefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.funcdef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncdef([NotNull] Python3Parser.FuncdefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameters([NotNull] Python3Parser.ParametersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameters([NotNull] Python3Parser.ParametersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.typedargslist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypedargslist([NotNull] Python3Parser.TypedargslistContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.typedargslist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypedargslist([NotNull] Python3Parser.TypedargslistContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.tfpdef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTfpdef([NotNull] Python3Parser.TfpdefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.tfpdef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTfpdef([NotNull] Python3Parser.TfpdefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.varargslist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarargslist([NotNull] Python3Parser.VarargslistContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.varargslist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarargslist([NotNull] Python3Parser.VarargslistContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.vfpdef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVfpdef([NotNull] Python3Parser.VfpdefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.vfpdef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVfpdef([NotNull] Python3Parser.VfpdefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStmt([NotNull] Python3Parser.StmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStmt([NotNull] Python3Parser.StmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.simple_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSimple_stmt([NotNull] Python3Parser.Simple_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.simple_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSimple_stmt([NotNull] Python3Parser.Simple_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.small_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSmall_stmt([NotNull] Python3Parser.Small_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.small_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSmall_stmt([NotNull] Python3Parser.Small_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.expr_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr_stmt([NotNull] Python3Parser.Expr_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.expr_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr_stmt([NotNull] Python3Parser.Expr_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.annassign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAnnassign([NotNull] Python3Parser.AnnassignContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.annassign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAnnassign([NotNull] Python3Parser.AnnassignContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.testlist_star_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTestlist_star_expr([NotNull] Python3Parser.Testlist_star_exprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.testlist_star_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTestlist_star_expr([NotNull] Python3Parser.Testlist_star_exprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.augassign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAugassign([NotNull] Python3Parser.AugassignContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.augassign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAugassign([NotNull] Python3Parser.AugassignContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.del_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDel_stmt([NotNull] Python3Parser.Del_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.del_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDel_stmt([NotNull] Python3Parser.Del_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.pass_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPass_stmt([NotNull] Python3Parser.Pass_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.pass_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPass_stmt([NotNull] Python3Parser.Pass_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.flow_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFlow_stmt([NotNull] Python3Parser.Flow_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.flow_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFlow_stmt([NotNull] Python3Parser.Flow_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.break_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBreak_stmt([NotNull] Python3Parser.Break_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.break_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBreak_stmt([NotNull] Python3Parser.Break_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.continue_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterContinue_stmt([NotNull] Python3Parser.Continue_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.continue_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitContinue_stmt([NotNull] Python3Parser.Continue_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.return_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturn_stmt([NotNull] Python3Parser.Return_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.return_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturn_stmt([NotNull] Python3Parser.Return_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.yield_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterYield_stmt([NotNull] Python3Parser.Yield_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.yield_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitYield_stmt([NotNull] Python3Parser.Yield_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.raise_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRaise_stmt([NotNull] Python3Parser.Raise_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.raise_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRaise_stmt([NotNull] Python3Parser.Raise_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.import_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImport_stmt([NotNull] Python3Parser.Import_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.import_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImport_stmt([NotNull] Python3Parser.Import_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.import_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImport_name([NotNull] Python3Parser.Import_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.import_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImport_name([NotNull] Python3Parser.Import_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.import_from"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImport_from([NotNull] Python3Parser.Import_fromContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.import_from"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImport_from([NotNull] Python3Parser.Import_fromContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.import_as_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImport_as_name([NotNull] Python3Parser.Import_as_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.import_as_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImport_as_name([NotNull] Python3Parser.Import_as_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.dotted_as_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDotted_as_name([NotNull] Python3Parser.Dotted_as_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.dotted_as_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDotted_as_name([NotNull] Python3Parser.Dotted_as_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.import_as_names"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImport_as_names([NotNull] Python3Parser.Import_as_namesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.import_as_names"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImport_as_names([NotNull] Python3Parser.Import_as_namesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.dotted_as_names"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDotted_as_names([NotNull] Python3Parser.Dotted_as_namesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.dotted_as_names"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDotted_as_names([NotNull] Python3Parser.Dotted_as_namesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.dotted_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDotted_name([NotNull] Python3Parser.Dotted_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.dotted_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDotted_name([NotNull] Python3Parser.Dotted_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.global_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGlobal_stmt([NotNull] Python3Parser.Global_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.global_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGlobal_stmt([NotNull] Python3Parser.Global_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.nonlocal_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNonlocal_stmt([NotNull] Python3Parser.Nonlocal_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.nonlocal_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNonlocal_stmt([NotNull] Python3Parser.Nonlocal_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.assert_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssert_stmt([NotNull] Python3Parser.Assert_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.assert_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssert_stmt([NotNull] Python3Parser.Assert_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.compound_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompound_stmt([NotNull] Python3Parser.Compound_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.compound_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompound_stmt([NotNull] Python3Parser.Compound_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.async_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAsync_stmt([NotNull] Python3Parser.Async_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.async_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAsync_stmt([NotNull] Python3Parser.Async_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.if_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIf_stmt([NotNull] Python3Parser.If_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.if_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIf_stmt([NotNull] Python3Parser.If_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.while_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhile_stmt([NotNull] Python3Parser.While_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.while_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhile_stmt([NotNull] Python3Parser.While_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.for_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFor_stmt([NotNull] Python3Parser.For_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.for_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFor_stmt([NotNull] Python3Parser.For_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.try_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTry_stmt([NotNull] Python3Parser.Try_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.try_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTry_stmt([NotNull] Python3Parser.Try_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.with_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWith_stmt([NotNull] Python3Parser.With_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.with_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWith_stmt([NotNull] Python3Parser.With_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.with_item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWith_item([NotNull] Python3Parser.With_itemContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.with_item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWith_item([NotNull] Python3Parser.With_itemContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.except_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExcept_clause([NotNull] Python3Parser.Except_clauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.except_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExcept_clause([NotNull] Python3Parser.Except_clauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.suite"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSuite([NotNull] Python3Parser.SuiteContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.suite"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSuite([NotNull] Python3Parser.SuiteContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.test"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTest([NotNull] Python3Parser.TestContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.test"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTest([NotNull] Python3Parser.TestContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.test_nocond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTest_nocond([NotNull] Python3Parser.Test_nocondContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.test_nocond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTest_nocond([NotNull] Python3Parser.Test_nocondContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.lambdef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLambdef([NotNull] Python3Parser.LambdefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.lambdef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLambdef([NotNull] Python3Parser.LambdefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.lambdef_nocond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLambdef_nocond([NotNull] Python3Parser.Lambdef_nocondContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.lambdef_nocond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLambdef_nocond([NotNull] Python3Parser.Lambdef_nocondContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.or_test"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOr_test([NotNull] Python3Parser.Or_testContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.or_test"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOr_test([NotNull] Python3Parser.Or_testContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.and_test"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAnd_test([NotNull] Python3Parser.And_testContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.and_test"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAnd_test([NotNull] Python3Parser.And_testContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.not_test"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNot_test([NotNull] Python3Parser.Not_testContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.not_test"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNot_test([NotNull] Python3Parser.Not_testContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.comparison"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComparison([NotNull] Python3Parser.ComparisonContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.comparison"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComparison([NotNull] Python3Parser.ComparisonContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.comp_op"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComp_op([NotNull] Python3Parser.Comp_opContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.comp_op"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComp_op([NotNull] Python3Parser.Comp_opContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.star_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStar_expr([NotNull] Python3Parser.Star_exprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.star_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStar_expr([NotNull] Python3Parser.Star_exprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr([NotNull] Python3Parser.ExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr([NotNull] Python3Parser.ExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.xor_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterXor_expr([NotNull] Python3Parser.Xor_exprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.xor_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitXor_expr([NotNull] Python3Parser.Xor_exprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.and_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAnd_expr([NotNull] Python3Parser.And_exprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.and_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAnd_expr([NotNull] Python3Parser.And_exprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.shift_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterShift_expr([NotNull] Python3Parser.Shift_exprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.shift_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitShift_expr([NotNull] Python3Parser.Shift_exprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.arith_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArith_expr([NotNull] Python3Parser.Arith_exprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.arith_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArith_expr([NotNull] Python3Parser.Arith_exprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTerm([NotNull] Python3Parser.TermContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTerm([NotNull] Python3Parser.TermContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFactor([NotNull] Python3Parser.FactorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFactor([NotNull] Python3Parser.FactorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.power"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPower([NotNull] Python3Parser.PowerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.power"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPower([NotNull] Python3Parser.PowerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.atom_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAtom_expr([NotNull] Python3Parser.Atom_exprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.atom_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAtom_expr([NotNull] Python3Parser.Atom_exprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAtom([NotNull] Python3Parser.AtomContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAtom([NotNull] Python3Parser.AtomContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.testlist_comp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTestlist_comp([NotNull] Python3Parser.Testlist_compContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.testlist_comp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTestlist_comp([NotNull] Python3Parser.Testlist_compContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.trailer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTrailer([NotNull] Python3Parser.TrailerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.trailer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTrailer([NotNull] Python3Parser.TrailerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.subscriptlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSubscriptlist([NotNull] Python3Parser.SubscriptlistContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.subscriptlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSubscriptlist([NotNull] Python3Parser.SubscriptlistContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.subscript_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSubscript_([NotNull] Python3Parser.Subscript_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.subscript_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSubscript_([NotNull] Python3Parser.Subscript_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.sliceop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSliceop([NotNull] Python3Parser.SliceopContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.sliceop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSliceop([NotNull] Python3Parser.SliceopContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.exprlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprlist([NotNull] Python3Parser.ExprlistContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.exprlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprlist([NotNull] Python3Parser.ExprlistContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.testlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTestlist([NotNull] Python3Parser.TestlistContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.testlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTestlist([NotNull] Python3Parser.TestlistContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.dictorsetmaker"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDictorsetmaker([NotNull] Python3Parser.DictorsetmakerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.dictorsetmaker"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDictorsetmaker([NotNull] Python3Parser.DictorsetmakerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.classdef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassdef([NotNull] Python3Parser.ClassdefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.classdef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassdef([NotNull] Python3Parser.ClassdefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.arglist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArglist([NotNull] Python3Parser.ArglistContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.arglist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArglist([NotNull] Python3Parser.ArglistContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgument([NotNull] Python3Parser.ArgumentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgument([NotNull] Python3Parser.ArgumentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.comp_iter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComp_iter([NotNull] Python3Parser.Comp_iterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.comp_iter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComp_iter([NotNull] Python3Parser.Comp_iterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.comp_for"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComp_for([NotNull] Python3Parser.Comp_forContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.comp_for"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComp_for([NotNull] Python3Parser.Comp_forContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.comp_if"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComp_if([NotNull] Python3Parser.Comp_ifContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.comp_if"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComp_if([NotNull] Python3Parser.Comp_ifContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.encoding_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEncoding_decl([NotNull] Python3Parser.Encoding_declContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.encoding_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEncoding_decl([NotNull] Python3Parser.Encoding_declContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.yield_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterYield_expr([NotNull] Python3Parser.Yield_exprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.yield_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitYield_expr([NotNull] Python3Parser.Yield_exprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.yield_arg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterYield_arg([NotNull] Python3Parser.Yield_argContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.yield_arg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitYield_arg([NotNull] Python3Parser.Yield_argContext context);
}
