//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from PythonParser.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;


/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="PythonParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
//[System.CLSCompliant(false)]
public interface IPythonParserListener : IParseTreeListener
{
    /// <summary>
    /// Enter a parse tree produced by <see cref="PythonParser.root"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterRoot([NotNull] PythonParser.RootContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="PythonParser.root"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitRoot([NotNull] PythonParser.RootContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="PythonParser.single_input"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterSingle_input([NotNull] PythonParser.Single_inputContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="PythonParser.single_input"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitSingle_input([NotNull] PythonParser.Single_inputContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="PythonParser.file_input"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterFile_input([NotNull] PythonParser.File_inputContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="PythonParser.file_input"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitFile_input([NotNull] PythonParser.File_inputContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="PythonParser.eval_input"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterEval_input([NotNull] PythonParser.Eval_inputContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="PythonParser.eval_input"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitEval_input([NotNull] PythonParser.Eval_inputContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="PythonParser.stmt"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterStmt([NotNull] PythonParser.StmtContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="PythonParser.stmt"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitStmt([NotNull] PythonParser.StmtContext context);
    /// <summary>
    /// Enter a parse tree produced by the <c>if_stmt</c>
    /// labeled alternative in <see cref="PythonParser.compound_stmt"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterIf_stmt([NotNull] PythonParser.If_stmtContext context);
    /// <summary>
    /// Exit a parse tree produced by the <c>if_stmt</c>
    /// labeled alternative in <see cref="PythonParser.compound_stmt"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitIf_stmt([NotNull] PythonParser.If_stmtContext context);
    /// <summary>
    /// Enter a parse tree produced by the <c>while_stmt</c>
    /// labeled alternative in <see cref="PythonParser.compound_stmt"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterWhile_stmt([NotNull] PythonParser.While_stmtContext context);
    /// <summary>
    /// Exit a parse tree produced by the <c>while_stmt</c>
    /// labeled alternative in <see cref="PythonParser.compound_stmt"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitWhile_stmt([NotNull] PythonParser.While_stmtContext context);
    /// <summary>
    /// Enter a parse tree produced by the <c>for_stmt</c>
    /// labeled alternative in <see cref="PythonParser.compound_stmt"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterFor_stmt([NotNull] PythonParser.For_stmtContext context);
    /// <summary>
    /// Exit a parse tree produced by the <c>for_stmt</c>
    /// labeled alternative in <see cref="PythonParser.compound_stmt"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitFor_stmt([NotNull] PythonParser.For_stmtContext context);
    /// <summary>
    /// Enter a parse tree produced by the <c>try_stmt</c>
    /// labeled alternative in <see cref="PythonParser.compound_stmt"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterTry_stmt([NotNull] PythonParser.Try_stmtContext context);
    /// <summary>
    /// Exit a parse tree produced by the <c>try_stmt</c>
    /// labeled alternative in <see cref="PythonParser.compound_stmt"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitTry_stmt([NotNull] PythonParser.Try_stmtContext context);
    /// <summary>
    /// Enter a parse tree produced by the <c>with_stmt</c>
    /// labeled alternative in <see cref="PythonParser.compound_stmt"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterWith_stmt([NotNull] PythonParser.With_stmtContext context);
    /// <summary>
    /// Exit a parse tree produced by the <c>with_stmt</c>
    /// labeled alternative in <see cref="PythonParser.compound_stmt"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitWith_stmt([NotNull] PythonParser.With_stmtContext context);
    /// <summary>
    /// Enter a parse tree produced by the <c>class_or_func_def_stmt</c>
    /// labeled alternative in <see cref="PythonParser.compound_stmt"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterClass_or_func_def_stmt([NotNull] PythonParser.Class_or_func_def_stmtContext context);
    /// <summary>
    /// Exit a parse tree produced by the <c>class_or_func_def_stmt</c>
    /// labeled alternative in <see cref="PythonParser.compound_stmt"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitClass_or_func_def_stmt([NotNull] PythonParser.Class_or_func_def_stmtContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="PythonParser.suite"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterSuite([NotNull] PythonParser.SuiteContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="PythonParser.suite"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitSuite([NotNull] PythonParser.SuiteContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="PythonParser.decorator"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterDecorator([NotNull] PythonParser.DecoratorContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="PythonParser.decorator"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitDecorator([NotNull] PythonParser.DecoratorContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="PythonParser.elif_clause"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterElif_clause([NotNull] PythonParser.Elif_clauseContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="PythonParser.elif_clause"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitElif_clause([NotNull] PythonParser.Elif_clauseContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="PythonParser.else_clause"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterElse_clause([NotNull] PythonParser.Else_clauseContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="PythonParser.else_clause"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitElse_clause([NotNull] PythonParser.Else_clauseContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="PythonParser.finally_clause"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterFinally_clause([NotNull] PythonParser.Finally_clauseContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="PythonParser.finally_clause"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitFinally_clause([NotNull] PythonParser.Finally_clauseContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="PythonParser.with_item"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterWith_item([NotNull] PythonParser.With_itemContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="PythonParser.with_item"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitWith_item([NotNull] PythonParser.With_itemContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="PythonParser.except_clause"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterExcept_clause([NotNull] PythonParser.Except_clauseContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="PythonParser.except_clause"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitExcept_clause([NotNull] PythonParser.Except_clauseContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="PythonParser.classdef"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterClassdef([NotNull] PythonParser.ClassdefContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="PythonParser.classdef"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitClassdef([NotNull] PythonParser.ClassdefContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="PythonParser.funcdef"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterFuncdef([NotNull] PythonParser.FuncdefContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="PythonParser.funcdef"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitFuncdef([NotNull] PythonParser.FuncdefContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="PythonParser.typedargslist"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterTypedargslist([NotNull] PythonParser.TypedargslistContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="PythonParser.typedargslist"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitTypedargslist([NotNull] PythonParser.TypedargslistContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="PythonParser.args"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterArgs([NotNull] PythonParser.ArgsContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="PythonParser.args"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitArgs([NotNull] PythonParser.ArgsContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="PythonParser.kwargs"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterKwargs([NotNull] PythonParser.KwargsContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="PythonParser.kwargs"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitKwargs([NotNull] PythonParser.KwargsContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="PythonParser.def_parameters"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterDef_parameters([NotNull] PythonParser.Def_parametersContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="PythonParser.def_parameters"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitDef_parameters([NotNull] PythonParser.Def_parametersContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="PythonParser.def_parameter"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterDef_parameter([NotNull] PythonParser.Def_parameterContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="PythonParser.def_parameter"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitDef_parameter([NotNull] PythonParser.Def_parameterContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="PythonParser.named_parameter"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterNamed_parameter([NotNull] PythonParser.Named_parameterContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="PythonParser.named_parameter"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitNamed_parameter([NotNull] PythonParser.Named_parameterContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="PythonParser.simple_stmt"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterSimple_stmt([NotNull] PythonParser.Simple_stmtContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="PythonParser.simple_stmt"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitSimple_stmt([NotNull] PythonParser.Simple_stmtContext context);
    /// <summary>
    /// Enter a parse tree produced by the <c>expr_stmt</c>
    /// labeled alternative in <see cref="PythonParser.small_stmt"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterExpr_stmt([NotNull] PythonParser.Expr_stmtContext context);
    /// <summary>
    /// Exit a parse tree produced by the <c>expr_stmt</c>
    /// labeled alternative in <see cref="PythonParser.small_stmt"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitExpr_stmt([NotNull] PythonParser.Expr_stmtContext context);
    /// <summary>
    /// Enter a parse tree produced by the <c>print_stmt</c>
    /// labeled alternative in <see cref="PythonParser.small_stmt"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterPrint_stmt([NotNull] PythonParser.Print_stmtContext context);
    /// <summary>
    /// Exit a parse tree produced by the <c>print_stmt</c>
    /// labeled alternative in <see cref="PythonParser.small_stmt"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitPrint_stmt([NotNull] PythonParser.Print_stmtContext context);
    /// <summary>
    /// Enter a parse tree produced by the <c>del_stmt</c>
    /// labeled alternative in <see cref="PythonParser.small_stmt"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterDel_stmt([NotNull] PythonParser.Del_stmtContext context);
    /// <summary>
    /// Exit a parse tree produced by the <c>del_stmt</c>
    /// labeled alternative in <see cref="PythonParser.small_stmt"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitDel_stmt([NotNull] PythonParser.Del_stmtContext context);
    /// <summary>
    /// Enter a parse tree produced by the <c>pass_stmt</c>
    /// labeled alternative in <see cref="PythonParser.small_stmt"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterPass_stmt([NotNull] PythonParser.Pass_stmtContext context);
    /// <summary>
    /// Exit a parse tree produced by the <c>pass_stmt</c>
    /// labeled alternative in <see cref="PythonParser.small_stmt"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitPass_stmt([NotNull] PythonParser.Pass_stmtContext context);
    /// <summary>
    /// Enter a parse tree produced by the <c>break_stmt</c>
    /// labeled alternative in <see cref="PythonParser.small_stmt"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterBreak_stmt([NotNull] PythonParser.Break_stmtContext context);
    /// <summary>
    /// Exit a parse tree produced by the <c>break_stmt</c>
    /// labeled alternative in <see cref="PythonParser.small_stmt"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitBreak_stmt([NotNull] PythonParser.Break_stmtContext context);
    /// <summary>
    /// Enter a parse tree produced by the <c>continue_stmt</c>
    /// labeled alternative in <see cref="PythonParser.small_stmt"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterContinue_stmt([NotNull] PythonParser.Continue_stmtContext context);
    /// <summary>
    /// Exit a parse tree produced by the <c>continue_stmt</c>
    /// labeled alternative in <see cref="PythonParser.small_stmt"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitContinue_stmt([NotNull] PythonParser.Continue_stmtContext context);
    /// <summary>
    /// Enter a parse tree produced by the <c>return_stmt</c>
    /// labeled alternative in <see cref="PythonParser.small_stmt"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterReturn_stmt([NotNull] PythonParser.Return_stmtContext context);
    /// <summary>
    /// Exit a parse tree produced by the <c>return_stmt</c>
    /// labeled alternative in <see cref="PythonParser.small_stmt"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitReturn_stmt([NotNull] PythonParser.Return_stmtContext context);
    /// <summary>
    /// Enter a parse tree produced by the <c>raise_stmt</c>
    /// labeled alternative in <see cref="PythonParser.small_stmt"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterRaise_stmt([NotNull] PythonParser.Raise_stmtContext context);
    /// <summary>
    /// Exit a parse tree produced by the <c>raise_stmt</c>
    /// labeled alternative in <see cref="PythonParser.small_stmt"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitRaise_stmt([NotNull] PythonParser.Raise_stmtContext context);
    /// <summary>
    /// Enter a parse tree produced by the <c>yield_stmt</c>
    /// labeled alternative in <see cref="PythonParser.small_stmt"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterYield_stmt([NotNull] PythonParser.Yield_stmtContext context);
    /// <summary>
    /// Exit a parse tree produced by the <c>yield_stmt</c>
    /// labeled alternative in <see cref="PythonParser.small_stmt"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitYield_stmt([NotNull] PythonParser.Yield_stmtContext context);
    /// <summary>
    /// Enter a parse tree produced by the <c>import_stmt</c>
    /// labeled alternative in <see cref="PythonParser.small_stmt"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterImport_stmt([NotNull] PythonParser.Import_stmtContext context);
    /// <summary>
    /// Exit a parse tree produced by the <c>import_stmt</c>
    /// labeled alternative in <see cref="PythonParser.small_stmt"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitImport_stmt([NotNull] PythonParser.Import_stmtContext context);
    /// <summary>
    /// Enter a parse tree produced by the <c>from_stmt</c>
    /// labeled alternative in <see cref="PythonParser.small_stmt"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterFrom_stmt([NotNull] PythonParser.From_stmtContext context);
    /// <summary>
    /// Exit a parse tree produced by the <c>from_stmt</c>
    /// labeled alternative in <see cref="PythonParser.small_stmt"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitFrom_stmt([NotNull] PythonParser.From_stmtContext context);
    /// <summary>
    /// Enter a parse tree produced by the <c>global_stmt</c>
    /// labeled alternative in <see cref="PythonParser.small_stmt"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterGlobal_stmt([NotNull] PythonParser.Global_stmtContext context);
    /// <summary>
    /// Exit a parse tree produced by the <c>global_stmt</c>
    /// labeled alternative in <see cref="PythonParser.small_stmt"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitGlobal_stmt([NotNull] PythonParser.Global_stmtContext context);
    /// <summary>
    /// Enter a parse tree produced by the <c>exec_stmt</c>
    /// labeled alternative in <see cref="PythonParser.small_stmt"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterExec_stmt([NotNull] PythonParser.Exec_stmtContext context);
    /// <summary>
    /// Exit a parse tree produced by the <c>exec_stmt</c>
    /// labeled alternative in <see cref="PythonParser.small_stmt"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitExec_stmt([NotNull] PythonParser.Exec_stmtContext context);
    /// <summary>
    /// Enter a parse tree produced by the <c>assert_stmt</c>
    /// labeled alternative in <see cref="PythonParser.small_stmt"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterAssert_stmt([NotNull] PythonParser.Assert_stmtContext context);
    /// <summary>
    /// Exit a parse tree produced by the <c>assert_stmt</c>
    /// labeled alternative in <see cref="PythonParser.small_stmt"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitAssert_stmt([NotNull] PythonParser.Assert_stmtContext context);
    /// <summary>
    /// Enter a parse tree produced by the <c>nonlocal_stmt</c>
    /// labeled alternative in <see cref="PythonParser.small_stmt"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterNonlocal_stmt([NotNull] PythonParser.Nonlocal_stmtContext context);
    /// <summary>
    /// Exit a parse tree produced by the <c>nonlocal_stmt</c>
    /// labeled alternative in <see cref="PythonParser.small_stmt"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitNonlocal_stmt([NotNull] PythonParser.Nonlocal_stmtContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="PythonParser.testlist_star_expr"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterTestlist_star_expr([NotNull] PythonParser.Testlist_star_exprContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="PythonParser.testlist_star_expr"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitTestlist_star_expr([NotNull] PythonParser.Testlist_star_exprContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="PythonParser.star_expr"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterStar_expr([NotNull] PythonParser.Star_exprContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="PythonParser.star_expr"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitStar_expr([NotNull] PythonParser.Star_exprContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="PythonParser.assign_part"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterAssign_part([NotNull] PythonParser.Assign_partContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="PythonParser.assign_part"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitAssign_part([NotNull] PythonParser.Assign_partContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="PythonParser.exprlist"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterExprlist([NotNull] PythonParser.ExprlistContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="PythonParser.exprlist"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitExprlist([NotNull] PythonParser.ExprlistContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="PythonParser.import_as_names"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterImport_as_names([NotNull] PythonParser.Import_as_namesContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="PythonParser.import_as_names"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitImport_as_names([NotNull] PythonParser.Import_as_namesContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="PythonParser.import_as_name"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterImport_as_name([NotNull] PythonParser.Import_as_nameContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="PythonParser.import_as_name"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitImport_as_name([NotNull] PythonParser.Import_as_nameContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="PythonParser.dotted_as_names"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterDotted_as_names([NotNull] PythonParser.Dotted_as_namesContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="PythonParser.dotted_as_names"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitDotted_as_names([NotNull] PythonParser.Dotted_as_namesContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="PythonParser.dotted_as_name"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterDotted_as_name([NotNull] PythonParser.Dotted_as_nameContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="PythonParser.dotted_as_name"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitDotted_as_name([NotNull] PythonParser.Dotted_as_nameContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="PythonParser.test"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterTest([NotNull] PythonParser.TestContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="PythonParser.test"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitTest([NotNull] PythonParser.TestContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="PythonParser.varargslist"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterVarargslist([NotNull] PythonParser.VarargslistContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="PythonParser.varargslist"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitVarargslist([NotNull] PythonParser.VarargslistContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="PythonParser.vardef_parameters"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterVardef_parameters([NotNull] PythonParser.Vardef_parametersContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="PythonParser.vardef_parameters"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitVardef_parameters([NotNull] PythonParser.Vardef_parametersContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="PythonParser.vardef_parameter"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterVardef_parameter([NotNull] PythonParser.Vardef_parameterContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="PythonParser.vardef_parameter"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitVardef_parameter([NotNull] PythonParser.Vardef_parameterContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="PythonParser.varargs"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterVarargs([NotNull] PythonParser.VarargsContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="PythonParser.varargs"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitVarargs([NotNull] PythonParser.VarargsContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="PythonParser.varkwargs"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterVarkwargs([NotNull] PythonParser.VarkwargsContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="PythonParser.varkwargs"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitVarkwargs([NotNull] PythonParser.VarkwargsContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="PythonParser.logical_test"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterLogical_test([NotNull] PythonParser.Logical_testContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="PythonParser.logical_test"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitLogical_test([NotNull] PythonParser.Logical_testContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="PythonParser.comparison"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterComparison([NotNull] PythonParser.ComparisonContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="PythonParser.comparison"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitComparison([NotNull] PythonParser.ComparisonContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="PythonParser.expr"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterExpr([NotNull] PythonParser.ExprContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="PythonParser.expr"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitExpr([NotNull] PythonParser.ExprContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="PythonParser.atom"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterAtom([NotNull] PythonParser.AtomContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="PythonParser.atom"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitAtom([NotNull] PythonParser.AtomContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="PythonParser.dictorsetmaker"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterDictorsetmaker([NotNull] PythonParser.DictorsetmakerContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="PythonParser.dictorsetmaker"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitDictorsetmaker([NotNull] PythonParser.DictorsetmakerContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="PythonParser.testlist_comp"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterTestlist_comp([NotNull] PythonParser.Testlist_compContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="PythonParser.testlist_comp"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitTestlist_comp([NotNull] PythonParser.Testlist_compContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="PythonParser.testlist"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterTestlist([NotNull] PythonParser.TestlistContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="PythonParser.testlist"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitTestlist([NotNull] PythonParser.TestlistContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="PythonParser.dotted_name"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterDotted_name([NotNull] PythonParser.Dotted_nameContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="PythonParser.dotted_name"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitDotted_name([NotNull] PythonParser.Dotted_nameContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="PythonParser.name"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterName([NotNull] PythonParser.NameContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="PythonParser.name"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitName([NotNull] PythonParser.NameContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="PythonParser.number"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterNumber([NotNull] PythonParser.NumberContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="PythonParser.number"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitNumber([NotNull] PythonParser.NumberContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="PythonParser.integer"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterInteger([NotNull] PythonParser.IntegerContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="PythonParser.integer"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitInteger([NotNull] PythonParser.IntegerContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="PythonParser.yield_expr"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterYield_expr([NotNull] PythonParser.Yield_exprContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="PythonParser.yield_expr"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitYield_expr([NotNull] PythonParser.Yield_exprContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="PythonParser.yield_arg"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterYield_arg([NotNull] PythonParser.Yield_argContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="PythonParser.yield_arg"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitYield_arg([NotNull] PythonParser.Yield_argContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="PythonParser.trailer"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterTrailer([NotNull] PythonParser.TrailerContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="PythonParser.trailer"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitTrailer([NotNull] PythonParser.TrailerContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="PythonParser.arguments"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterArguments([NotNull] PythonParser.ArgumentsContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="PythonParser.arguments"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitArguments([NotNull] PythonParser.ArgumentsContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="PythonParser.arglist"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterArglist([NotNull] PythonParser.ArglistContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="PythonParser.arglist"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitArglist([NotNull] PythonParser.ArglistContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="PythonParser.argument"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterArgument([NotNull] PythonParser.ArgumentContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="PythonParser.argument"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitArgument([NotNull] PythonParser.ArgumentContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="PythonParser.subscriptlist"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterSubscriptlist([NotNull] PythonParser.SubscriptlistContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="PythonParser.subscriptlist"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitSubscriptlist([NotNull] PythonParser.SubscriptlistContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="PythonParser.subscript"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterSubscript([NotNull] PythonParser.SubscriptContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="PythonParser.subscript"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitSubscript([NotNull] PythonParser.SubscriptContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="PythonParser.sliceop"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterSliceop([NotNull] PythonParser.SliceopContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="PythonParser.sliceop"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitSliceop([NotNull] PythonParser.SliceopContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="PythonParser.comp_for"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterComp_for([NotNull] PythonParser.Comp_forContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="PythonParser.comp_for"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitComp_for([NotNull] PythonParser.Comp_forContext context);
    /// <summary>
    /// Enter a parse tree produced by <see cref="PythonParser.comp_iter"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void EnterComp_iter([NotNull] PythonParser.Comp_iterContext context);
    /// <summary>
    /// Exit a parse tree produced by <see cref="PythonParser.comp_iter"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    void ExitComp_iter([NotNull] PythonParser.Comp_iterContext context);
}

